### ISSUE TITLE
Allow Caching of Nested Routes

### ISSUE THREAD

**Issue by srsgores** [racido/broccoli-manifest#11]
Currently, the implementation only works for the top-level ``/`` domain, but if you try to view a resource offline like ``/posts``, since there's no ``posts/index.html`` cached, you will get the offline  page.

I have tried editing the ``fallback`` section to serve ``index.html``, but this still fails because the browser will request ``manifest.appcache`` from the nested domain, so ``resource/manifest.appcache``.  My next idea was to duplicate the top-level assets and files in the ``manifest.appcache``, and **this worked**, but the problem was that this new appcache generated from the nested resource **was overwriting** the appcache initially created on the top-level (``/``).

Are there any suggestions on configuring nested resources/routes to work in a SPA application?  Perhaps this isn't related to this particular plugin, but I thought it might be useful to explain that this plugin cannot deal with nested resources.

**Comment by ssured** [comment]
I use `locationType: 'hash'` in the Ember config, which solves the issue for me.
