### ISSUE TITLE
Not working in Chrome?

### ISSUE THREAD

**Issue by Baukereg** [racido/broccoli-manifest#12]
I've implemented broccoli-manifest in a test project and tested with success in Firefox and IE when I kill the server. Yet it doesn't seem to work in the latest version of Chrome. I still get the 'This webpage is not available' message.

I followed all installation steps. The ember-cli-build (the new broccoli file) file looks like this:

```
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var mergeTrees = require('broccoli-merge-trees');
var writeManifest = require('broccoli-manifest');
var writeServiceWorker = require('broccoli-serviceworker');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
  });
  
  var completeTree = app.toTree()

  return mergeTrees([completeTree, writeManifest(completeTree), writeServiceWorker(completeTree)]);
};
```

**Comment by ssured** [comment]
Works for me in Chrome too. The reason might be that you have your console open? There is a setting which blocks all caching in Chrome when the console is open. Handy during development, but not for testing the cache...

**Comment by ssured** [comment]
Did you resolve this? If not please reopen
