### ISSUE TITLE
Fingerprint assets

### ISSUE THREAD

**Issue by oligriffiths** [racido/broccoli-manifest#15]
Would it make sense to fingerprint the assets in the manifest. If they're stored in the local browser cache, but they've changed, the mainfest will be updated, but the asset may not be. Not sure the internal workings of if an asset has changed whether it gets re-loaded when the manifest changes...

**Comment by krachtstefan** [comment]
Hi @oligriffiths. I'm using broccoli-manifest with ember-cli and as far as I can see the assets in the manifest are fingerprinted if [fingerprint is enabled in your current build setup](broccoli-manifest).

**Comment by ssured** [comment]
The default setting of Ember CLI is to fingerprint assets. This plugin follows the settings of Ember CLI, it does work with fingerprinted assets. I'll close this issue for now. Please reopen if you are having difficulty in working with fingerprinted assets.
